version: '3.7'
services:
  DB:
    image: mongo:latest
    container_name: DB
    restart: always
    ports:
      - 27017:27017
    

volumes:
  myvolume:
    driver: local

networks:
  default:
    external:
      name: mynetwork
